extern int register_num;
extern int label_num;
int getReg();
void freeReg();
int getLabel();
int code_gen(struct tnode* t,FILE* target_file);
void read_code_gen(struct tnode* t,FILE* target_file);
void write_code_gen(struct tnode* t, FILE* target_file);
void store_stack(int value,FILE* target_file);
void if_code_gen(struct tnode* t,FILE* target_file);
void while_code_gen(struct tnode* t,FILE* target_file);
int evaluator(struct tnode* t);